blank_issues_enabled: false
contact_links:
  - name: KhulnaSoft Lab Feedback
    url: https://github.com/khulnasoft-lab/feedback/discussions
    about: Share your feedback with the KhulnaSoft DevOps Lab.
